//putting in an empty makefile fn

//I'm thinking it'll be easier to get a makefile going so in case this gets run on PCs w/e we don't all need the XCode project file to run this on an IDE. 
//we can just run it on Linux?? 
